export const mockUser = {
  id: '1',
  name: 'Alysia Dermott',
  email: 'alysia@learnify.com',
  avatar: '/placeholder-user.jpg',
  hoursSpent: 21200,
  coursesCompleted: 12,
  averageScore: 196,
}

export const mockCourses = [
  {
    id: '1',
    title: 'Mobile Design',
    category: 'Design',
    progress: 65,
    hours: 40,
    color: 'bg-blue-50',
    badge: 'bg-blue-100 text-lab-primary-blue',
    icon: '📱',
    description: 'Learn mobile UI/UX design principles',
    instructor: 'Sarah Johnson',
    students: 1500,
    rating: 4.8,
    price: 4900,
    duration: '8 weeks',
    level: 'Beginner',
    lessons: 24,
    completed: 16,
  },
  {
    id: '2',
    title: 'UX Design Foundations',
    category: 'Design',
    progress: 45,
    hours: 35,
    color: 'bg-purple-50',
    badge: 'bg-purple-100 text-lab-accent-purple',
    icon: '✨',
    description: 'Master the fundamentals of user experience design',
    instructor: 'Michael Chen',
    students: 2300,
    rating: 4.9,
    price: 4900,
    duration: '10 weeks',
    level: 'Beginner',
    lessons: 32,
    completed: 14,
  },
  {
    id: '3',
    title: 'UI Components',
    category: 'Design',
    progress: 70,
    hours: 28,
    color: 'bg-amber-50',
    badge: 'bg-amber-100 text-yellow-900',
    icon: '🎨',
    description: 'Design beautiful and functional UI components',
    instructor: 'Emma Wilson',
    students: 1200,
    rating: 4.7,
    price: 4900,
    duration: '6 weeks',
    level: 'Intermediate',
    lessons: 20,
    completed: 14,
  },
  {
    id: '4',
    title: 'Web Development Basics',
    category: 'Development',
    progress: 0,
    hours: 0,
    color: 'bg-green-50',
    badge: 'bg-green-100 text-lab-success-green',
    icon: '💻',
    description: 'Start your web development journey',
    instructor: 'David Miller',
    students: 3500,
    rating: 4.8,
    price: 3900,
    duration: '12 weeks',
    level: 'Beginner',
    lessons: 48,
    completed: 0,
  },
  {
    id: '5',
    title: 'Project Management',
    category: 'Business',
    progress: 0,
    hours: 0,
    color: 'bg-red-50',
    badge: 'bg-red-100 text-lab-error-red',
    icon: '📊',
    description: 'Lead projects like a pro',
    instructor: 'Lisa Anderson',
    students: 890,
    rating: 4.6,
    price: 2900,
    duration: '8 weeks',
    level: 'Intermediate',
    lessons: 28,
    completed: 0,
  },
  {
    id: '6',
    title: 'Advanced CSS',
    category: 'Development',
    progress: 0,
    hours: 0,
    color: 'bg-indigo-50',
    badge: 'bg-indigo-100 text-indigo-900',
    icon: '🎯',
    description: 'Master modern CSS techniques',
    instructor: 'James Brown',
    students: 2100,
    rating: 4.9,
    price: 3500,
    duration: '6 weeks',
    level: 'Advanced',
    lessons: 36,
    completed: 0,
  },
]

export const mockAssignments = [
  {
    id: '1',
    title: 'Typography Test',
    course: 'Mobile Design',
    score: '192/200',
    status: 'Completed',
    dueDate: 'Today, 12:30 AM',
    completedDate: 'Today, 10:30 AM',
  },
  {
    id: '2',
    title: 'Inclusive Design Test',
    course: 'UX Design Foundations',
    score: '196/200',
    status: 'Completed',
    dueDate: 'Today, 1:30 PM',
    completedDate: 'Today, 11:45 AM',
  },
  {
    id: '3',
    title: 'Typography Test',
    course: 'UI Components',
    score: null,
    status: 'Upcoming',
    dueDate: 'Tomorrow, 2:30 AM',
    completedDate: null,
  },
]

export const mockLessons = [
  {
    id: '1',
    title: 'Introduction to Mobile Design',
    duration: 45,
    completed: true,
    course: 'Mobile Design',
  },
  {
    id: '2',
    title: 'Design Systems & Components',
    duration: 60,
    completed: true,
    course: 'Mobile Design',
  },
  {
    id: '3',
    title: 'User Research & Testing',
    duration: 55,
    completed: false,
    course: 'Mobile Design',
  },
  {
    id: '4',
    title: 'Color Theory & Typography',
    duration: 50,
    completed: false,
    course: 'UX Design Foundations',
  },
]

export const categories = ['All Courses', 'Design', 'Development', 'Business', 'Marketing']

export const mockBlogs = [
  {
    id: '1',
    title: '10 Essential UX Design Principles Every Designer Should Know',
    excerpt: 'Discover the fundamental principles that make great user experiences. Learn from industry experts about what makes design truly impactful.',
    author: 'Michael Chen',
    date: '2026-02-03',
    category: 'Design',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '5 min read',
    featured: true,
    color: 'bg-blue-100',
    sticker: '🎨',
  },
  {
    id: '2',
    title: 'The Future of Web Development: AI and Automation',
    excerpt: 'How artificial intelligence is transforming web development and what skills you need to master in the AI era.',
    author: 'David Miller',
    date: '2026-02-01',
    category: 'Development',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '8 min read',
    featured: true,
    color: 'bg-green-100',
    sticker: '🤖',
  },
  {
    id: '3',
    title: 'Project Management Tips for Remote Teams',
    excerpt: 'Master the art of managing distributed teams with these proven strategies and tools used by successful companies.',
    author: 'Lisa Anderson',
    date: '2026-01-30',
    category: 'Business',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '6 min read',
    featured: false,
    color: 'bg-yellow-100',
    sticker: '📊',
  },
  {
    id: '4',
    title: 'CSS Grid vs Flexbox: When to Use Each',
    excerpt: 'A deep dive into modern CSS layout techniques and when to choose one over the other for optimal results.',
    author: 'James Brown',
    date: '2026-01-28',
    category: 'Development',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '7 min read',
    featured: false,
    color: 'bg-pink-100',
    sticker: '⚡',
  },
  {
    id: '5',
    title: 'User Research Methods That Actually Work',
    excerpt: 'Learn the most effective user research techniques to validate your design decisions and build products users love.',
    author: 'Sarah Johnson',
    date: '2026-01-25',
    category: 'Design',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '9 min read',
    featured: false,
    color: 'bg-purple-100',
    sticker: '🔍',
  },
  {
    id: '6',
    title: 'Building Better Learning Platforms: Case Studies',
    excerpt: 'Explore how top educational platforms are innovating to create engaging and effective learning experiences.',
    author: 'Emma Wilson',
    date: '2026-01-22',
    category: 'Design',
    image: '/placeholder.svg?height=300&width=400',
    readTime: '10 min read',
    featured: true,
    color: 'bg-orange-100',
    sticker: '📚',
  },
]
